### ISSUE TITLE
Enable Actions so a build test can be added

### ISSUE THREAD

**Issue by huard** [CSHS-CWRA/RavenHydroFramework#18]
### Addressing a Problem?

It would be useful if PRs triggered builds of Raven, so it's clear whether a PR breaks the installation. 

### Potential Solution

The code is already [there](https://github.com/CSHS-CWRA/RavenHydroFramework/blob/main/.github/workflows/testing.yml), it just needs to be activated. 

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by Zeitsperre** [comment]
There's a linting step included to ensure that PRs follow the guidelines that are used for RHF, but I need input on what rules specifically are in place (beyond 2-space tabbing).

If coding standards aren't as important, we can disable all but those we care about.
