### ISSUE TITLE
Reservoir evaporation incorrectly reported as zero in ReservoirMassBalance.csv

### ISSUE THREAD

**Issue by BernardoTeufel** [CSHS-CWRA/RavenHydroFramework#21]
### Setup Information

- Raven version: 3.6
- Operating System: Ubuntu 20.04

### Description

For all reservoirs in the domain, the `sub???????.evap..m3.` columns in `ReservoirMassBalance.csv` are filled with zeros. However, evaporation is occurring, as evidenced by the `sub???????.MB.error..m3.` in the same file, which is strongly related to PET in the `ForcingFunctions.csv` file (relationship is not perfect given that the watershed-average PET is not equal to the PET for each HRU/lake).

Scatterplot of MB error vs PET, red line is theoretical relationship based on lake surface area:
![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/472a5ebf-7150-48e8-ba86-ffd0acdba500)

MB error over 20 days (mid-June to early July), red line is PET scaled by lake surface area:
![image](https://github.com/CSHS-CWRA/RavenHydroFramework/assets/146113799/57585bd4-50f4-4a4a-8409-24bbf452f175)

Edit: confirmed relationship to OW PET by setting `:OW_Evaporation PET_CONSTANT`, which results in constant MB errors for all reservoirs.
 

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by analytophile** [comment]
could you verify this still occurs with the most recent version of the source code? I believe this was fixed after v3.6, and suggestions here should solely address the most recent release versions.

**Comment by BernardoTeufel** [comment]
Issue
