### ISSUE TITLE
Comma used as blank in Pollutographs.csv

### ISSUE THREAD

**Issue by BernardoTeufel** [CSHS-CWRA/RavenHydroFramework#27]
### Setup Information

- Raven version: v453 (latest)
- Operating System: Ubuntu 20.04

When discharge is zero in Hydrographs.csv, the corresponding concentration in Pollutographs.csv is undefined (as expected). However, the character used to represent this case in Pollutographs.csv is `,`, which complicates parsing the file. 

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by analytophile** [comment]
fixed in newest source. Thanks for tracking these down!
