### ISSUE TITLE
Zero outflow of constituents from reservoirs

### ISSUE THREAD

**Issue by BernardoTeufel** [CSHS-CWRA/RavenHydroFramework#28]
### Setup Information

- Raven version: v453 (latest)
- Operating System: Ubuntu 20.04

Starting from runoff routing:
```
:HydrologicProcesses
  :Precipitation     PRECIP_RAVEN             ATMOS_PRECIP     PONDED_WATER          
  :Flush             RAVEN_DEFAULT            PONDED_WATER     SURFACE_WATER         
:EndHydrologicProcesses
```

Added the following lines to the .rvi file:
```
:Transport MRROS
:FixedConcentration MRROS ATMOS_PRECIP 0.1
```

For all headwater subbasins without reservoir, the Pollutograph is as expected (constant value of 0.1). For subbasins with reservoir (headwater or not), the Pollutograph is essentially zero - typical values range from -1e-12 to -1e-6. 

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by BernardoTeufel** [comment]
Issue is caused by unspecified `DECAY_COEFF`, which defaults to -33333.3 and results in negative mass (which results in concentrations reported as ~0). Fixed by setting negative values of `DECAY_COEFF` to zero.

**Comment by analytophile** [comment]
updated fix now in main code.
