### ISSUE TITLE
Report error codes to `stderr`

### ISSUE THREAD

**Issue by Zeitsperre** [CSHS-CWRA/RavenHydroFramework#34]
### Addressing a Problem?

When I try to determine whether Raven was successfully run, I have to manually read and parse the output. This doesn't really help when performing tests from Python or on CI.

Additionally, for terminal messages that aren't errors, the message should not loudly say `Error Code` as this is confusing to users (related issue #25).

### Potential Solution

For error codes that denote failure of the program (runtime or user errors), the message should be sent to `stderr` instead of `stdout`. 

### Additional context

https://www.systutorials.com/how-to-print-a-line-to-stderr-and-stdout-in-c-2/

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by analytophile** [comment]
done in newest update.
