### ISSUE TITLE
Report Reservoir Net Inflow in Hydrographs.csv/.nc output file

### ISSUE THREAD

**Issue by analytophile** [CSHS-CWRA/RavenHydroFramework#6]
### Potential Solution

in addition to the gross inflow, it would be useful to report the reservoir net inflow (Qin+P-ET) as a column in the Hydrograph file.

Request from M. Han at OPG.

### Additional context

This may have cascading effects to RavenR  and other utilities which assume a fixed set of column data items reported for each subbasin

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by dustming** [comment]
Hi James @analytophile  

     I have added this functionality by following the steps: 
      - Fork the latest Raven master branch at (https://github.com/dustming/RavenHydroFramework)
      - modify the StandardOutput.cpp. 
     I am unsure if we want to include these updates in the Raven master branch. If we do, what procedure should I follow to create a pull request? 

Thanks 
Ming

**Comment by analytophile** [comment]
Hi Ming,
Please confirm it was just StandardOutput.cpp that was revised, and I'll integrate it in as an output option.
Cheers,
James

**Comment by analytophile** [comment]
Never mind. Just confirmed myself, cleaned up and added to the trunk.
